name: bot

on:
  workflow_call:
    inputs:
      cargo_loc:
        default: '0'
        required: true
        type: string
      cargo_bin:
        default: '0'
        required: true
        type: string
      external:
        default: ''
        required: false
        type: string
      note_hash:
        default: 'None'
        required: false
        type: string

jobs:
  ready:
    uses: ./.github/workflows/cargo-version.yml
    with:
      cargo_path: ${{ inputs.cargo_loc }}

  push:
    needs:
      - ready
    uses: ./.github/workflows/create-tag.yml
    with:
      version: v${{ needs.ready.outputs.version }}

  publish:
    needs:
      - push
    uses: ./.github/workflows/pre-release.yml
    with:
      push_tag: ${{ needs.push.outputs.tag }}
      note: add ${{ needs.push.outputs.tag }}

  cross-release:
    needs:
      - publish
    uses: ./.github/workflows/_ccw.yml
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            platform: macos-latest
          -
            target: 'x86_64-apple-darwin'
            platform: 'macos-latest'
          -
            target: 'x86_64-pc-windows-gnu'
            platform: 'windows-latest'
    with:
      binary: ${{ inputs.cargo_bin }}
      pushed_tag: ${{ needs.publish.outputs.pushed_tag }}
      target: ${{ matrix.target }}
      platform: ${{ matrix.platform }}
    
