name: Create-tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string
    outputs:
      tag:
        description: "Pushed tag version"
        value: ${{ jobs.call.outputs.tag }}

jobs:
  call:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.push.outputs.tag }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: push
        run: |
          version="${{ inputs.version }}"
          git tag $version && git push --tags
          echo tag=$version >> $GITHUB_OUTPUT
        name: Push Tag
        shell: bash