name: cross-compile-upload

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      pushed_tag:
        default: '0'
        required: true
        type: string
      platform:
        default: 'ubuntu-latest'
        required: true
        type: string
      target:
        default: 'x86_64-unknown-linux-gnu'
        required: true
        type: string
      binary:
        default: 'bin'
        required: true
        type: string

jobs:
  cross-release:
    name: publish - ${{ inputs.target }}
    runs-on: ${{ inputs.platform }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        uses: taiki-e/upload-rust-binary-action@v1.16.0
        with:
          bin: ${{ inputs.binary }}
          target: ${{ inputs.target }}
          ref: refs/tags/${{ inputs.pushed_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
        name: Upload release