name: release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      push_tag:
        default: '0'
        required: true
        type: string
      note:
        default: 'None'
        required: true
        type: string
    outputs:
      pushed_tag:
        description: "Pushed tag version"
        value: ${{ jobs.release.outputs.pushed_tag }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Release
        run: |
          gh release create $PUSH_TAG --notes $NOTES
          echo pushed_tag=$PUSH_TAG >> $GITHUB_OUTPUT
        shell: bash
        env:
          PUSH_TAG: ${{ inputs.push_tag }}
          NOTES: "${{ inputs.note }}"