name: tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string
    outputs:
      pushed_tag:
        description: "Pushed tag version"
        value: ${{ jobs.call.outputs.push_tag }}

jobs:
  call:
    runs-on: ubuntu-latest
    outputs:
          push_tag: ${{ steps.push.outputs.tag }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: push
        run: |
          tag="${{ inputs.version }}"
          git tag $tag && git push --tags
          echo tag=$tag >> $GITHUB_OUTPUT
        name: Push Tag
        shell: bash